### ISSUE TITLE
After creating a gallery item, I can't get rid of the green alert box

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#1801] opened 2014-11-19 20:48 UTC
I just created a number of gallery items. After done, a green alert box appears. I click on the 'X' on that gallery item, but it doesn't make it go away; i.e. it doesn't seem to work. 

![screen shot 2014-11-19 at 3 46 59 pm](https://cloud.githubusercontent.com/assets/953118/5114085/7df51dc0-7003-11e4-8543-e03f77c19d0d.png)

**Comment by cjhendrix** [comment] 2015-03-19 13:38
Duplicate of #1653.  Closing.

**Closed by cjhendrix** 2015-03-19 13:38 UTC
Labels: bug, Priority-Low
