### ISSUE TITLE
Private datasets don't have a private dataset icon

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#1593] opened 2014-10-24 16:35 UTC
In the "my datasets" page, private datasets **do have** a private dataset icon. However, after you click on that dataset there isn't an icon. I can see the dataset is private by looking at "Visibility: private", but was wondering if it would be nicer to have an icon right next to the title ...

**Comment by cjhendrix** [comment] 2014-12-09 12:53
Sorry @ochadataproject , this one fell through the cracks.  

Here is the view on the dashboard (default CKAN labeling of "private" and "deleted")

![image](https://cloud.githubusercontent.com/assets/1654485/5357529/1ff35fc4-7fa9-11e4-861f-93db26f39514.png)

The proposed solution is to add a similar functionality to the dataset view page:

![image](https://cloud.githubusercontent.com/assets/1654485/5357674/af670592-7faa-11e4-87f1-3ff37d65ce99.png)

**Comment by cjhendrix** [comment] 2015-02-26 10:01
Pinging @ochadataproject @yumiendo if this is an ok solution once the issue is prioritized for action.

**Comment by ochadataproject** [comment] 2015-02-26 16:52
thanks CJ, looks fine. How does it work with the dataset page that shows
'deleted' since we dont archive the data? also no need to copy Yumi on
pre-existing issues. If I need her help I will bring her in.

thanks

**Comment by cjhendrix** [comment] 2015-02-27 12:29
We don't archive old versions of a resource (if you upload a new version of spreadsheet to the same resource, the old version is gone).  However, it's actually not possible to _really_ delete things on ckan, they are just marked as deleted in the database.    So a deleted dataset is still in the database, with the last version of its resources and visible only to org members on the org page.

**Comment by yumiendo** [comment] 2015-09-08 22:28
added the lock icon(svg) to the google drive
https://drive.google.com/open?id=0B24NBcgmV490VjFQMFRoZ3V3VXc
and sorry for stupid question but what does 'deleted' mean?? if you delete something...why can we still see it?

**Comment by luiscape** [comment] 2015-09-09 02:35
@yumiendo jumping on here, in CKAN nothing is ever really deleted. If an user deletes something, only that user will be able to "see" that dataset. That user and system administrators, like us. The advantage of that is that if an user makes a mistake we can "undelete" pretty much anything using the API.

**Comment by teodorescuserban** [comment] 2015-09-09 04:36
Remember "Recycle Bin"?

Mie, 9 sept. 2015, 05:35, Luis Capelo notifications@github.com a scris:

**Comment by danmihaila** [comment] 2015-09-09 12:48
@teodorescuserban it is like Recycle Bin, but there is not "empty recycle bin" button :)

**Comment by teodorescuserban** [comment] 2015-09-09 12:48
yes it is. I got a big red one :)
willing to share the knowledge about it :)

În Mie, 9 sept. 2015 la 15:48, danmihaila notifications@github.com a
scris:

**Comment by yumiendo** [comment] 2015-09-09 14:24
thanks guys for the info.
I just tested deleting my dummy data...I do see a 'deleted' label on dataset page. 

2 questions:
1. am I supposed to be able to click on the label to revive data? (right now it doesnt....)
2. if 'deleted' is not actionable - where do i go to revive data? (I couldnt find it)

I didn't see 'deleted' on dashboard after deleting the file - is it supposed to appear there too? (my dataset - 3rd screenshot) 

<img width="1440" alt="screen shot 2015-09-09 at 10 28 01 am" src="https://cloud.githubusercontent.com/assets/8006323/9764400/f33cc518-56dc-11e5-8c4e-73c623036803.png">
<img width="1440" alt="screen shot 2015-09-09 at 10 28 47 am" src="https://cloud.githubusercontent.com/assets/8006323/9764405/fa81173e-56dc-11e5-96c7-c70f5d99dcf1.png">
<img width="1440" alt="screen shot 2015-09-09 at 10 32 02 am" src="https://cloud.githubusercontent.com/assets/8006323/9764408/fe189cbe-56dc-11e5-9dd5-274e2b677a30.png">

**Comment by luiscape** [comment] 2015-09-09 14:26
@yumiendo I believe there isn't an option in the UI that allows an user to "revive" data. It is only available through the API to the final user at the moment ...

**Comment by cjhendrix** [comment] 2015-09-09 14:38
That's correct.  I like it when one ancient issue links to another ancient issue.  :)  #782  Happy we are digging down into these!

**Comment by yumiendo** [comment] 2015-09-09 14:40
ahaahaha I was just thinking about 'undelete' action. 
is this something people requested or would be useful to the data team?

**Comment by luiscape** [comment] 2015-09-09 14:44
@yumiendo at times we have to undelete datasets or resources. It comes around for the Data Team at least once every two months or so. Cc'ing @takavarasha so he can contribute.

**Comment by cjhendrix** [comment] 2015-09-09 14:49
From an interface perspective, I just made the issue about undelete because it seems weird to show users deleted datasets but not to give them the ability to undelete.   As far as  I know, no users have asked for it.

**Comment by yumiendo** [comment] 2015-09-09 14:55
@cjhendrix I agree...maybe its an option to make it visible to sys admin only?

**Comment by cjhendrix** [comment] 2015-09-09 15:09
I suggest that _if_ we are going to build a button for it, we can easily make it visible to both sysadmins and users who have rights on the dataset to be undeleted.

**Comment by teodorescuserban** [comment] 2015-09-09 16:22
There needs to be a research seeing what implications this delete /
undelete have around dataset names and history.

Just to be clear about the "Recycle Bin". From server console, I can either
"purge" a dataset or "undelete" it. Purge will remove it permanently, while
undelete will make it active again.

@luiscape if there are only a handful of datasets per month that need to be
purged / undeleted by the data team, I can take it on. @cjhendrix should be
able to know more if undelete on UI is worth considering.

În Mie, 9 sept. 2015 la 18:09, cjhendrix notifications@github.com a scris:

**Comment by luiscape** [comment] 2015-09-09 16:36
@yumiendo, @scraperdragon, @cjhendrix to make it clear, there is no feature request from the Data Team. This isn't much of a need nor a problem.

**Comment by teodorescuserban** [comment] 2015-09-09 16:37
:)

În Mie, 9 sept. 2015 la 19:36, Luis Capelo notifications@github.com a
scris:

**Comment by yumiendo** [comment] 2015-09-09 18:55
Sorry to side track from the main topic which is about private icon.

I find 'deleted' label strange without having a way to "undelete" a dataset and the fact that something I deleted doesn't go away kind of scares me. (original issue by CJ https://github.com/OCHA-DAP/hdx-ckan/issues/782)
but it sounds like ''undelete" functionality is NOT needed at the moment. 

(I just tried this and it's strange. I deleted dataset > the dataset says "deleted" > edited meta data > uploaded new dataset > the dataset still says "deleted")

so to make it easy - shall we REALLY delete(or do not display) dataset if its deleted @cjhendrix @luiscape @takavarasha ?

**Comment by luiscape** [comment] 2015-09-09 19:49
Hiding a dataset from a user if it is deleted seems reasonable to me. That is, that user would only be able to see that dataset if she knew the specific URL (or dataset id) of that dataset.

**Comment by takavarasha** [comment] 2015-09-10 12:29
I am of the opinion that in the absence of a recycle bin, a deletion must be permanent. There are many reasons why a user might want to delete something. Typical cases are they were doing tests and no longer need the dataset. There are more serious cases though, like when user uploads something sensitive or deeply personal (by mistake) and they just want to take it down. I can imagine the frustration that someone in that situation would feel when they realize that their mistake will not be going away.

Another issue to consider is that a deleted dataset keeps its url. The url is by default constructed from the title of the dataset. Sometimes users will simply want to delete an old dataset and replace it with a new one, which is a reasonable thing to do. However, there will be problems if they give the new dataset the same Title as the one they (or someone else) deleted. I can imagine trying to create a dataset and being told that it already exists, yet I was so sure I had deleted it. Then I search for it and I can't find it. Then go back to try and add it again and being told it already exists... This is rare but has happened several times already.

Finally, soft deletes like the one we currently have work well if there is a recycle bin. Most users are already familiar with how recycle bins work. I would suggest we maintain the soft delete, but add "restore" and "permanently delete" buttons to deleted datasets for users with privileges to edit the dataset in question.

**Comment by danmihaila** [comment] 2015-09-10 12:52
I think we should have a discussion about how to handle the deletion of different entities: dataset, location, organization, user in HDX CKAN. To compare it how it is in CKAN and what are our preferences and of course if we want to change what will be the implications...
@amcguire62 we should set a call with data team and try to figure out what we want and what is best scenario in our case.

**Comment by cjhendrix** [comment] 2015-09-11 08:56
Since @amcguire62 is on vacation at the moment, let me try an channel him.  :)  We got into this discussion because we are trying to action #2227.  And the topic of this issue (#1593) is closely related and could be solved at the same time.    These are purely about display of a dataset's status and not about the delete/recycle/undelete issue, so I suggest we split them.

This issue plus #2227:  display the icons and deleted/private badges on the dataset view page.  We can action that now, @yumiendo could you give us a design that takes into account both the icons and the private/deleted labels?

The much older (indeed default ckan) issue #782: we can discuss as Dan suggested (and I agree with @takavarasha proposed solution) but only if we think this is a real pain point for users (and @takavarasha describes a good case in which it would be).  Let's move the discussion on that to #782. Because it gets quite deep into the ckan db schema, it might be costly to solve, and I don't want it to hold up what could be a quick fix to #782 and #1593.

**Comment by cjhendrix** [comment] 2015-09-14 07:09
By the way, just FYI, I saw today that we _do_ show a deleted badge on the dataset view page.  Screen grab from staging is below.  

![image](https://cloud.githubusercontent.com/assets/1654485/9844033/381bea7e-5ac0-11e5-8f25-2e6a53008dfb.png)

**Comment by alexandru-m-g** [comment] 2015-09-14 08:24
@cjhendrix, I think it comes from here: https://github.com/OCHA-DAP/hdx-ckan/issues/356

**Comment by cjhendrix** [comment] 2015-09-14 12:17
Wow, we're going to start finding dinosaur fossils if we dig much further back . . .

**Comment by yumiendo** [comment] 2015-09-16 14:40
Two options to add private icon. 
@danmihaila - is it a lot of effort to make "my dataset" view like data list (option b)? 

option A. (quick fix)
Add private(lock) icon https://drive.google.com/open?id=0B24NBcgmV490VjFQMFRoZ3V3VXc
next to the title of dataset on
1.my dataset (dashboard, image below)
<img width="1403" alt="screen shot 2015-09-16 at 10 38 12 am" src="https://cloud.githubusercontent.com/assets/8006323/9907479/55a15ee6-5c5d-11e5-8ee6-040f5c015cc5.png">

2.(private) dataset page
<img width="1400" alt="screen shot 2015-09-16 at 10 45 53 am" src="https://cloud.githubusercontent.com/assets/8006323/9907689/5566df68-5c5e-11e5-8c53-32c29a931f16.png">

option B. (legit? fix)
currently the dashboard section is based on the old design (I believe the design was adopted based on other pages but not designed) 
1. my dataset (looks more like "data" list)
   <img width="1397" alt="screen shot 2015-09-16 at 10 51 01 am" src="https://cloud.githubusercontent.com/assets/8006323/9907852/06bad512-5c5f-11e5-8c05-62c1bc3f88c9.png">
2. (private) dataset page
   <img width="1400" alt="screen shot 2015-09-16 at 10 45 53 am" src="https://cloud.githubusercontent.com/assets/8006323/9907689/5566df68-5c5e-11e5-8c53-32c29a931f16.png">

For both options - private icon is separated from other icon group since its more important key to the owner.

**Comment by cjhendrix** [comment] 2015-09-17 08:31
Looks good to me. Option B if easy, option A if not, IMHO.

A couple of additional suggestions to make Yumi's fix cover all cases:

1) additionally put the private icon on the various flavors of search results on org, custom org, location, and custom location
2) @yumiendo, there will also be a deleted badge in some of these locations (see first screen cap on this issue).  Maybe we want a small icon for that and place it in the same place as the private icon?
3) There was a third, but it escaped my brain.

Once we get the details nailed down, I think we need to package it all up and present to @amcguire62 .

**Comment by yumiendo** [comment] 2015-09-17 15:05
@ochadataproject comp is as above. option B(legit fix) is preferred direction to streamline the design of all pages which is part of another issue... https://github.com/OCHA-DAP/hdx-ckan/issues/3555

**Comment by ochadataproject** [comment] 2015-09-17 17:47
thanks Yumi the private icon seems fine. I dont see the big difference
between A and B. We we do need to re-do the dashboard at some stage. Also I
know there was a long discussion about delete and undelete. How did we
resolve that?

**Comment by cjhendrix** [comment] 2015-09-18 08:01
Delete/Undelete is part of the #3555 issue that we prioritized yesterday (and the [4 or 5 other issues closely related to it](https://github.com/OCHA-DAP/hdx-ckan/labels/DatasetLists)).   By the time you read this we will have had the first call on breaking the work down.  I think the delete/undelete part will be the last piece to build, but we will have to decide what behavior we want this week so Yumi can design for it.  

The ideal solution is to have a recycle bin from which users could permanently delete or restore a dataset, but that's complex to build and users haven't been asking for this. 

So the current plan A is to see if we can make deletion permanent.  @takavarasha has summed up the reasons why this is important here https://github.com/OCHA-DAP/hdx-ckan/issues/1593#issuecomment-139221045

Plan A may also be complex (to be researched by someone on the dev team next sprint).  So plan B 
would be to simply make the deleted datasets invisible to users in any dataset list.  They would only see it if they navigate to the specific URL and are authorized to see it (it would have a "deleted" badge).  This is almost the current behavior now and would be relatively to implement. 

Tagging @amcguire62 since he's not on the participant list for this issue yet.

**Comment by danmihaila** [comment] 2016-04-26 10:58
@cjhendrix i think we can close this issue. tnx

**Closed** 2016-04-26 14:07 UTC
Labels: DatasetLists, FromHDXTeamUsers, Priority-Low
