### ISSUE TITLE
Strange formatting on Newsfeed entries

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3692] opened 2015-10-12 12:49 UTC
On stag

![image](https://cloud.githubusercontent.com/assets/1654485/10428256/5ff509cc-70f0-11e5-8916-9a2d0a3e95cc.png)

**Comment by teodorescuserban** [comment] 2015-10-12 12:52
Staging might be broken, you know? :)
Let me just do a fast redeploy.

În Lun, 12 oct. 2015 la 15:49, cjhendrix notifications@github.com a scris:

**Comment by teodorescuserban** [comment] 2015-10-12 12:53
Hmh, actually not many merges these days. Only Alex's checker.

În Lun, 12 oct. 2015 la 15:51, Serban Teodorescu <
teodorescu.serban@gmail.com> a scris:

**Comment by teodorescuserban** [comment] 2015-10-12 12:53
Redeployed staging, nevertheless.

În Lun, 12 oct. 2015 la 15:52, Serban Teodorescu <
teodorescu.serban@gmail.com> a scris:

**Comment by danmihaila** [comment] 2015-10-12 12:54
dataset with long names is breaking this. Pinging @yumiendo to consider this when redesign dashboard.

**Comment by yumiendo** [comment] 2015-10-12 14:00
thank you for this -
when does “New activity item” label show up? I just accessed my dashboard and the new item has a red dot next to it.
<img width="1440" alt="screen shot 2015-10-12 at 10 10 10 am" src="https://cloud.githubusercontent.com/assets/8006323/10429640/0a93c25c-70c8-11e5-9e49-85f9183cffb6.png">

**Comment by cjhendrix** [comment] 2015-10-21 09:54
Strange.  Seems I get the "new" label instead of the dot.

**Comment by danmihaila** [comment] 2015-10-21 10:35
it looks like a bug. @cjhendrix you might need to show @mbellotti how is happening in case she can not reproduce.

**Comment by mbellotti** [comment] 2015-10-27 05:38
Right... haven't been able to reproduce, but best guess from looking at the code is that the css stylesheet was not loading correctly. Changing default text to a \* which should work?

**Comment by danmihaila** [comment] 2015-11-03 10:59
@cjhendrix can you please test this on staging?

**Comment by cjhendrix** [comment] 2015-11-03 12:54
Still a bit weird:

![image](https://cloud.githubusercontent.com/assets/1654485/10908469/7c9346b8-8232-11e5-8848-69fd6f4f665e.png)

**Comment by danmihaila** [comment] 2015-11-03 14:38
low priority for the moment according to @amcguire62 , moving to sprint candidates

**Comment by yumiendo** [comment] 2015-11-03 16:16
i'd bring it up to the same height as tabs....

<img width="1400" alt="screen shot 2015-11-03 at 11 32 06 am" src="https://cloud.githubusercontent.com/assets/8006323/10913510/3e04b3de-821c-11e5-85e3-773ef3a737be.png">

**Closed as completed** 2016-04-20 12:26 UTC
Labels: Medium Priority
