### ISSUE TITLE
Location Page: add edit button for sysadmins

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2368] opened 2015-02-25 17:49 UTC
![image](https://cloud.githubusercontent.com/assets/1654485/6376574/a754bddc-bd16-11e4-8e68-51ba3813d540.png)

**Comment by danmihaila** [comment] 2015-05-13 09:11
this is a duplicate of #2540 . closing it

**Closed as completed by danmihaila** 2015-05-13 09:11 UTC
Labels: Low Priority
