### ISSUE TITLE
Contribute: making a dataset public causes error on location id

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#4147] opened 2016-03-04 09:25 UTC
Related to #2378 since I can only get it to happen with a new location.
1. Create a new group
2. Create a new private dataset assigned to your new group (I used a fake URL resource).  You may run into issue #2378 at this point.  
3. From the dataset view page, click "make it public"
4. The location field may or may not be populated.  The behavior is inconsistent.  Reloading the modal will sometimes change the behavior.  Sometimes the location field is populated, sometimes not.

**Comment by alexandru-m-g** [comment] 2016-05-26 21:46
I tested this both locally and on feature-data (https://feature-data.hdx.rwlabs.org/dataset/testing-dataset-acountryfortesting ) . I can't reproduce this problem. More so, there is code that specifically invalidates the cache when a new group is created. There's also a test, testing that. 

But I have the following scenario in mind, which @teodorescuserban might confirm if it's possible:
-  On production we actually run 2 CKANs on 2 different servers
-  Both have their own **internal (in python) cache** of locations/groups
-  When a new group is created the cache is invalidated only on one of the 2 CKANs
-  So whenever you hit the other server you might still get responses from the old cache

@cjhendrix in any case, can you still reproduce this ?

**Comment by cjhendrix** [comment] 2016-05-27 07:15
I'm pretty sure this is related to #2378, so I'll wait until we fix that to try and reproduce this one.   but I like you're theory.  It would make sense.

**Comment by alexandru-m-g** [comment] 2016-05-27 11:37
@teodorescuserban I need your help. I can't reproduce this locally at all. CJ, managed to reproduce the problem on demo. Any ideas ? 
This is the same problem as #2378

**Comment by alexandru-m-g** [comment] 2016-06-06 09:27
This should be closed by fixing #2378

**Closed as completed by alexandru-m-g** 2016-06-06 09:27 UTC
Labels: Medium Priority
