### ISSUE TITLE
CSS issue with the deleting dataset confirmation page

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#2939] opened 2015-06-11 16:53 UTC
After clicking on "Delete" on a dataset page, I am directed to a confirmation page that asks me to confirm if I really want to do that. When I got there I saw this page that had some broken CSS: 

![screen shot 2015-06-11 at 12 45 49 pm](https://cloud.githubusercontent.com/assets/953118/8112915/e58f3800-1038-11e5-8155-56ae78bbc527.png)

**Comment by teodorescuserban** [comment] 2015-06-11 16:55
+1

**Comment by cjhendrix** [comment] 2015-06-12 10:48
duplicate of #2922   :p

**Closed as completed by cjhendrix** 2015-06-12 10:48 UTC
