### ISSUE TITLE
New locations not consistently appearing in dropdown on dataset create/edit

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2378] opened 2015-02-27 12:28 UTC
#### initial description form @cjhendrix

Sometimes it's there, sometimes not.  Sometimes a refresh helps, sometimes not. Weird.
#### How to reproduce it

Create a location (group). Then go to dataset create/edit and check if that location appears in dropdown.
#### Nosetest
- create new location
- get group list using the action to see if that group exists
- check if the dropdown is using other action or way to get the list of groups

**Comment by danmihaila** [comment] 2015-03-03 16:10
@cjhendrix I need some more info about this issue

**Comment by cjhendrix** [comment] 2015-03-03 16:12
Can you check with Alex?  He and I tested it toegether last week.

**Comment by danmihaila** [comment] 2015-03-03 16:13
pinging @alexandru-m-g

**Comment by cjhendrix** [comment] 2015-04-25 18:27
Let's fix this before the next big crisis.  Makes it hard to set up new crisis pages.

**Comment by mbellotti** [comment] 2015-05-20 16:53
Okay I can't reproduce this issue. Not on staging, not on dev, not locally either. My best guess is that it's a caching problem, but I've tried multiple times on each environment and it's just not happening.

**Comment by danmihaila** [comment] 2015-05-22 13:29
@cjhendrix I also tested on staging and local. I can not reproduce it. Can you please try it again and if you can reproduce it please tell us the steps (user, etc)

**Comment by cjhendrix** [comment] 2015-05-22 15:22
Still happening for me.  On Windows 8 Chrome (and just to be thorough on my Lenovo laptop):
1. Log in as sysadmin (myself in this case)
2. go to /group/new
3. create "Tatooine" and save
4. click "contribute"
5. search for Tatooine in the dropdown, **it's not there**
6. type up this issue for two minutes, then think it would be good to confirm it exists
7. load /group/tatooine in a new tab.  It exists.
8. refresh the dataset create page
9. search for Tatooine in the dropdown, **it's there!**
10. open an existing dataset and edit (https://test-data.hdx.rwlabs.org/dataset/edit/raw-fts-input in this example)
11. try adding Tatooine to the dataset.  **it's not there**
    ![image](https://cloud.githubusercontent.com/assets/1654485/7773737/c48f484e-00a6-11e5-8df6-9d40c4e3538c.png)
12. open another existing dataset and edit (https://test-data.hdx.rwlabs.org/dataset/edit/ebola-cases-2014 in this example)
13. try adding Tatooine to the dataset **It's there!**
    ![image](https://cloud.githubusercontent.com/assets/1654485/7773788/e7d33108-00a6-11e5-9bbb-1d7cb86581f3.png)

As a further note, during the first day after the Nepal Earthquake, we created /group/nepal-earthquake and I systematically went through about 15 datasets to add that location.  I frequently wouldn't appear, but when I would try again later, it would appear. Very strange. And very frustrating during a crisis.

**Comment by mbellotti** [comment] 2015-05-22 15:45
Is the Lenovo Linux based or also Windows 8? Because there does appear to
be some wonkiness between Windows 8 and Chrome:

https://productforums.google.com/forum/#!topic/chrome/c4i8WfJIoyA

Can you open up the inspector, load the dataset create page and tell us
what X-Cache response headers say?

**Comment by danmihaila** [comment] 2015-05-25 08:32
moving to Sprint 56 as it needs more testing

**Comment by cjhendrix** [comment] 2015-05-26 08:56
@mbellotti:  Here are the response headers from https://data.hdx.rwlabs.org/dataset/new?organization_id=0974463c-5419-4e89-9b55-90e035074ccf

Assigning back to you, but please assign to whoever was going to follow up on this one.

HTTP/1.1 200 OK
Server: nginx
Date: Tue, 26 May 2015 08:51:58 GMT
Content-Type: text/html; charset=utf-8
Cache-Control: private
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, PUT, GET, DELETE, OPTIONS
Access-Control-Allow-Headers: X-CKAN-API-KEY, Authorization, Content-Type
Content-Encoding: gzip
X-Cache: MISS from rp-c1.service.emergency.lu
X-Cache-Lookup: MISS from rp-c1.service.emergency.lu:80
Transfer-Encoding: chunked
Connection: keep-alive

**Comment by cjhendrix** [comment] 2015-12-02 10:09
This one is still happening.  I saw it several times yesterday when running the demos.  This could be a big problem when setting up a new group for a new crisis.  I've added it to sprint candidates so we can consider working on it again.

**Comment by cjhendrix** [comment] 2016-03-04 09:16
This is still happening with the new contribute flow.

**Comment by cjhendrix** [comment] 2016-05-27 09:44
reproduced on demo 27-May-2016

**Comment by danmihaila** [comment] 2016-05-30 09:17
together with @alexandru-m-g we found that the problem might be related to /api/action/cached_group_list and python cache and because we are using several processes on server side.
pinging @teodorescuserban 
We will follow with a call to brainstorm for a solution.

**Closed as completed** 2016-06-06 09:03 UTC
Labels: Bug, Medium Priority, Need Nosetest
