### ISSUE TITLE
In some cases, file resources are getting set to "Import from URL"

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#4105] opened 2016-02-22 17:50 UTC
It's not clear if this is a bug, or just some awkwardness in the new interface taht we haven't caught yet. 

From Slack discussion:
Seeing something odd.  The most recent resources in the dataset below have odd links for the download button and result in 404.  The download links look like `filename.csv/` (that's the full link).

https://data.hdx.rwlabs.org/dataset/refugee-and-returnee-data (31KB)
https://data.hdx.rwlabs.org/dataset/mauritania-fluctuations-chiffres-mberra-camp (31KB)

Other resources on the same dataset are ok.

Also here: https://data.hdx.rwlabs.org/dataset/niger-population-of-malian-refugees-and-fluctuations 

These are all private UNHCR datasets.  Other orgs private datasets are ok.  And public UNHCR datasets are ok.  Weird.

Looks like they are getting set (either by user or by a bug) as "import from URL"

**Comment by teodorescuserban** [comment] 2016-02-22 22:03
They look like they were create by a scripț (a buggy one). I remember
having similar issues în early stages of cod script.

**Comment by cjhendrix** [comment] 2016-02-23 08:24
Tagging @takavarasha @luiscape on this one since it _might_ some our scripts doing this.  If not, data team may want to contact someone at UNHCR responsible for their scripts.

**Comment by danmihaila** [comment] 2016-02-23 13:06
reproduced & found too by @aalecs and assigned to him.

**Comment by aalecs** [comment] 2016-02-23 13:21
What I found: 
- create new dataset by drag&droping a file
- for the resource select "Import from URL" 
- add any url and fill the rest of the required fields
- hit Save

Result:
- instead of having a resource with URL, the initial drag&dropped file is uploaded

@cjhendrix - does it sound like the users might have used this scenario to create those resources? I don't have the rights to view those datasets on prod, so I can't really check.

I'll commit the fix for the issue I described later on.

**Comment by cjhendrix** [comment] 2016-02-23 13:25
It's possible. Because they are private, the activity stream info isn't recorded.  But it is the most recently updated resource in every case.

**Comment by danmihaila** [comment] 2016-02-23 13:30
@aalecs check the first dataset  on staging: https://test-data.hdx.rwlabs.org/dataset/refugee-and-returnee-data
it is public

**Comment by aalecs** [comment] 2016-02-23 13:39
Thanks @danmihaila ... I checked it and it doesn't look to be caused by the bug I described. 
Might be the case that some scripts are doing this as CJ previously commented.

**Comment by danmihaila** [comment] 2016-02-26 12:19
this is done via hotfixes already deployed. to be reopen in case it appears again

**Closed as completed by danmihaila** 2016-02-26 12:19 UTC
Labels: Bug, High Priority, testedSTAG
