### ISSUE TITLE
Link to website previews as HTML text

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3825] opened 2015-11-17 11:50 UTC
In this dataset, the link is to a web page.  Preview is enabled and the displays the raw html.  Desired behavior would be to disable preview. 

https://data.hdx.rwlabs.org/dataset/crs-history-in-nepal

**Comment by danmihaila** [comment] 2016-03-01 13:43
this is not a bug. It is an external link (to a website) and marked as XML resource. CKAN is allowing you to preview a html page as xml :)
I think we can close this one

**Closed as completed** 2016-05-04 12:33 UTC
