### ISSUE TITLE
New icons flicker when hovered

### ISSUE THREAD

**Issue by luiscape** [OCHA-DAP/hdx-ckan#2267] opened 2015-02-05 22:16 UTC
On a MAC (and Chrome + Safari + Firefox), the icons are changing places slightly when hovered. Here is a gif:

![efe20c3705609a7a87245fd95c89e9f7](https://cloud.githubusercontent.com/assets/953118/6070468/a8c8b216-ad5a-11e4-8a9c-a4174092a673.gif)

**Comment by cjhendrix** [comment] 2015-02-06 16:53
Duplicate of  #2233 but I'm stealing your gif.  Again.

**Closed as completed by cjhendrix** 2015-02-06 16:53 UTC
