### ISSUE TITLE
Very slow downloads. 

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3164] opened 2015-07-21 11:55 UTC
I'm having trouble downloading even very small files (6kb)  Sometimes getting stuck in the "starting" phase (on Chrome) as shown below (up to 2m10s).

![image](https://cloud.githubusercontent.com/assets/1654485/8800003/2ad68cac-2faf-11e5-81c6-412a489e73fa.png)

Examples with the problem:
http://test-data.hdx.rwlabs.org/dataset/6b4532c9-8f4a-4824-9f78-f2c6aa0874fd/resource/1e824cc6-a03e-403d-8833-fc3be591c878/download/testcsvaaAen-utf8.csv

http://test-data.hdx.rwlabs.org/dataset/e66dbc70-17fe-4230-b9d6-855d192fc05c/resource/fb37281c-f0d1-43bd-a13d-b9cc9044dc47/download/col-idp-for-map.csv

http://test-data.hdx.rwlabs.org/dataset/805fea22-1fc0-4a8b-883c-eab088ae77b1/resource/aa59993d-6e22-486b-85a0-c8829afa8cd9/download/testcsvaaAen-utf8.csv

**Comment by teodorescuserban** [comment] 2015-07-21 11:57
Please try the urls directly with https and see if things get better.
Also, is your internet connection in good shape?
(I tried to replicate and the download is instant).

**Comment by danmihaila** [comment] 2015-07-21 12:13
@mbellotti do you have any advice on this?

**Comment by teodorescuserban** [comment] 2015-07-21 12:35
After more testing it appears our provider blocks the last byte of the file (the file download is complete but it is never reported as complete).

I emailed them to purge their cache and we will see.

**Comment by danmihaila** [comment] 2015-07-21 13:29
ok, @teodorescuserban pls ping back when this is done. I think we will also have to display the "https" download link

**Comment by teodorescuserban** [comment] 2015-07-22 18:05
Our provider is still investigating.
I made some tests with small csv on our feature stack installed yesterday on the new provider (for example the second url given by @cjhendrix, but of course replacing the hostname)
Of course I updated ckan first to the current version of the 2.3 branch.
It is working ok.

**Comment by teodorescuserban** [comment] 2015-07-22 22:39
Waiting for our provider to come up with a solution.
FTR the root cause appears to be an incompatibility between ckan and squid (more specific, the way squid handles HTTP/1.1 Chunked responses with Byte-Range headers when in reverse proxy setup).

**Comment by teodorescuserban** [comment] 2015-07-23 20:00
closing & tagging @cjhendrix

**Comment by teodorescuserban** [comment] 2015-07-23 20:00
The solution was to drop squid as reverse proxy and go with nginx.

**Closed as completed by teodorescuserban** 2015-07-23 20:00 UTC
Labels: CKAN 2.3, before-23deploy
