### ISSUE TITLE
Geo Preview: shape_info shows that the transform has started, but it never finishes

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3260] opened 2015-07-24 15:56 UTC
I ran all 6 of these updates back to back.  All finished except one, which shows that the transform is in progress, though the worker finished. I never saw more than 4 items in the queue, but they appeared slowly, so the first might have finished before the last was added. 

https://test-data.hdx.rwlabs.org/api/3/action/package_show?id=nepal-climate-data

**Comment by cjhendrix** [comment] 2015-07-24 17:23
The same thing happened here: https://data.hdx.rwlabs.org/dataset/nigeria-water-courses-cod

On test it worked fine (all three resources have geo preview)
On prod, the big one (first resource) has the "started" status, but the other two completed
I ran again on prod, and the geo  preview completed (very quickly!).

**Comment by cjhendrix** [comment] 2015-08-14 09:05
A few more casualties of this one:
https://test-data.hdx.rwlabs.org/api/3/action/package_show?id=lsib-simplified-shoreline
https://test-data.hdx.rwlabs.org/api/3/action/package_show?id=lsib-polygons-eurasia-and-oceania-simplified
https://test-data.hdx.rwlabs.org/api/3/action/package_show?id=lsib-polygons-africa-and-americas-simplified
https://test-data.hdx.rwlabs.org/dataset/syria-border-crossings

**Comment by alexandru-m-g** [comment] 2015-08-18 11:37
@cjhendrix @teodorescuserban 
All the examples from the comment above are from staging so they might be related to the fact that the geopreview transformation doesn't seem to work on staging. ( related to #3237 )

**Comment by teodorescuserban** [comment] 2015-08-19 21:32
**NOTE: This only affects staging**

After some fun hours of debugging with @alexandru-m-g and some changes in the gislayer code (by @alexandru-m-g ) we reach the following conclusions:
1. on python 2.7.6 (stock ubuntu 14.04) geopreview works if `VERIFIY_CKAN_SSL` is `False`
2. on python 2.7.10 (installed with pyenv) and rqworker started manually it works

In the process the following tests / changes have been made:
1. redirect from nginx from http to https changed from 301 to 307 (to preserve the `POST` after the redirect) - this made initially the call to update api fail with `Bad request - JSON Error: No request body data`
2. temp folder cleaning after successful task processing works
3. changed the `CKAN_SERVER_URL` pattern in template to reflect the current `HDX_PREFIX` and `HDX_DOMAIN`

While letting the `VERIFIY_CKAN_SSL` to `False`, I am still thinking on having 2.7.10 on python containers (with the possibility to switch the respective app if needed)

I let @alexandru-m-g close this one (and the ones related).

**Comment by alexandru-m-g** [comment] 2015-08-20 16:04
@cjhendrix the causes for the latest casualties where fixed.

**Closed as completed by alexandru-m-g** 2015-08-20 16:04 UTC
Labels: High Priority, GeoPreview
