### ISSUE TITLE
License description missing for FTS indicator datasets

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#3264] opened 2015-07-27 08:43 UTC
I'm not sure when it happened, but we seem to have lost the methodology description for the FTS country-centric datasets.  We have it in the indicator centric datasets, just not the country-centric ones.  

We need to write a patch or script to fix this across all country centric FTS datasets.   The methodology text is:

```
FTS encourages the use of its data and reports presented herein, for informational and analytical purposes. You can copy, download or print content for your own use, and you can also include FTS in your own documents, presentations, blogs, websites and teaching materials, provided that suitable acknowledgment of FTS as source is given. You should cite FTS, the publication date of the funding figures and site URL (uniform resource locator) as applicable.

See: http://fts.unocha.org/pageloader.aspx?page=contact-ContactUs&select=3
```

**Comment by cjhendrix** [comment] 2015-07-27 10:10
Actually, maybe it isn't all:  https://data.hdx.rwlabs.org/dataset/usa_fts_indicators

But definitely some: https://data.hdx.rwlabs.org/dataset/fra_fts_indicators

**Comment by danmihaila** [comment] 2015-07-29 07:45
@cjhendrix is it about methdology or license? the issue is not very clear for me the

**Comment by cjhendrix** [comment] 2015-07-29 08:11
Sorry, I confused myself.  it's about License.  Title edited.

**Comment by mbellotti** [comment] 2015-08-10 14:10
@luiscape any ideas how the data got broken?

**Comment by luiscape** [comment] 2015-08-10 14:28
@mbellotti no idea. I am unsure how CPS-generated-datasets (i.e. "indicators") are registered on HDX.

**Comment by danmihaila** [comment] 2015-08-10 14:42
lets have a call with @alexandru-m-g , maybe he has some comments re CPS.

**Comment by cjhendrix** [comment] 2015-08-11 12:09
@luiscape @takavarasha The original metadata for the FTS indicators came from our bootstrapping script, CKAN_setup.  Since then it looks like some have been changed, but not all of them.  We were wondering if you guys might remember running any batch processes (or manual ones) that could affect the license text for the FTS indicators.

**Comment by takavarasha** [comment] 2015-08-11 12:59
I do not recall myself doing any such updates. Maybe @luiscape may remember something.

**Comment by luiscape** [comment] 2015-08-11 13:01
@cjhendrix Now that you mention, I do remember a script written to add "Source: " to the description of indicator datasets. If I remember well, that script ran once or in an ad-hoc basis. I believe @takavarasha may have more details. 

I believe I haven't written anything that edits indicator datasets on HDX.

**Comment by mbellotti** [comment] 2015-08-18 21:47
So what's the next steps here? It's still assigned to me, but it sounds like this can be fixed more easily on the data team side?

**Comment by aalecs** [comment] 2015-08-26 11:47
@takavarasha Can you advise? Thanks!

**Comment by takavarasha** [comment] 2015-08-26 12:20
We will work on this but it is low priority for the data team at the moment.

Before launch in 2014, there was a script that I ran to update the description field on all curated datasets. The script added the source of the dataset to the description field for all datasets. It did not work on the licence and it affected all datasets not just FTS country centric. I do not think that the script was the source of the disappearing licence description.

**Comment by danmihaila** [comment] 2015-08-26 12:26
@aalecs we should move this one to Backlog and @takavarasha should get back to us when they addressed this one.

**Comment by danmihaila** [comment] 2016-05-04 11:57
@takavarasha any updates on this one?

**Closed as completed** 2016-05-04 12:36 UTC
Labels: Bug, Low Priority
