### ISSUE TITLE
Non-ascii characters in resource name may cause internal server error

### ISSUE THREAD

**Issue by takavarasha** [OCHA-DAP/hdx-ckan#3002] opened 2015-06-29 20:01 UTC
On production, attempting to download a resource whose name contains non-ascii characters may cause an internal server error if the extension of the resource is omitted in the name of the resource. The following steps will reproduce the behavior described above:

1 Edit the name of any resource on production to "My tést"
2 After saving the resource, click on the download link to download the resource
3 An internal server error occurs
4 Edit the name of the resource to "My tést.txt" (or another appropriate extension)
5 After saving the resource, click on the download link to download the resource
6. The resource download as expected if there is an extension
7. Finally, rename the resource to "My test" (no ascii chars and no extension)
8. Download the resource and the resource downloads as expected.

**Comment by mbellotti** [comment] 2015-09-18 13:52
Update on the status of this: So far I cannot reproduce it either locally or on staging. I can't reproduce it on production either, but weirdly production will not let me rename files at all. I'll be looking at the logs today to try to get to the bottom of this.

**Comment by teodorescuserban** [comment] 2015-09-18 13:53
Will provide logs and support @mbellotti in 4 hours.

În Vin, 18 sept. 2015 la 16:52, mbellotti notifications@github.com a
scris:

**Comment by takavarasha** [comment] 2015-09-18 14:30
I just tested this out on production and the bug is no longer present

**Comment by teodorescuserban** [comment] 2015-09-18 15:33
I think it might be related to the ussue you had, Godfrey with new org req.

Vin, 18 sept. 2015, 17:30, Godfrey Takavarasha notifications@github.com a
scris:

**Comment by danmihaila** [comment] 2015-09-21 13:13
closing it

**Closed as completed by danmihaila** 2015-09-21 13:13 UTC
Labels: Bug, Medium Priority, testedSTAG
