### ISSUE TITLE
unable to create custom org page

### ISSUE THREAD

**Issue by reubano** [OCHA-DAP/hdx-ckan#2965] opened 2015-06-23 12:44 UTC
https://data.hdx.rwlabs.org/organization/ocha-somalia

Steps:
- Enable the custom org flag (sysadmin)
- Edit custom org settings (admin)
- Click 'update organization' (admin)
- Page redirects to regular org page
- Click edit (admin)
- Custom org flag not present and custom settings are gone

**Comment by danmihaila** [comment] 2015-06-23 12:49
@reubano can you please specify what user you used to set the custom org?

**Comment by reubano** [comment] 2015-06-23 12:52
CJ enabled the flag, I edited the settings. Is that what you mean?

**Comment by danmihaila** [comment] 2015-06-23 13:56
After chatting with @reubano we found the problem is related to "admin" role.
1. Custom org is enabled by a sysadmin.
2. The admin of the org is editing, but there is no checkbox displayed to set flag about custom org.

**Comment by alexandru-m-g** [comment] 2015-06-23 14:00
I think that's how the initial requirements were: #2298

**Comment by danmihaila** [comment] 2015-08-27 12:21
closing this one

**Closed as completed by danmihaila** 2015-08-27 12:21 UTC
