### ISSUE TITLE
at least one country have no polygon

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/hdx-ckan#2266] opened 2015-02-05 19:53 UTC
rou have no polygon attached.

when going to https://data.hdx.rwlabs.org/group/rou?sort=metadata_modified+desc the map zooms out on a multiworld level. no polygon in sight.

**Comment by luiscape** [comment] 2015-02-05 22:12
Maybe the problem is caused by a confusion of using `ROU` instead of the [deprecated](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) `ROM`?

**Comment by cjhendrix** [comment] 2015-02-06 10:09
We had a few geojson problems that were fixed in #2156.   Closing this one.

**Closed as completed by cjhendrix** 2015-02-06 10:09 UTC
Labels: testedSTAG
