### ISSUE TITLE
user related database issue with duplicating rows

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/hdx-ckan#3656] opened 2015-10-01 23:02 UTC
It seems that sometimes duplicates appear in the database for **validation_tokens** table and for **user_extra** table. Check below:

```
select * from validation_tokens where user_id='77ba0d4e-bc8d-4ae5-b0e2-848feafadadf';
                 id                  |               user_id                |              token               | valid 
--------------------------------------+--------------------------------------+----------------------------------+-------
4a3cbc86-b90a-47d4-8ea6-b845b987d676 | 77ba0d4e-bc8d-4ae5-b0e2-848feafadadf | TOKEN                | f
6ac999b9-1bae-4cf0-93ec-817546f166b2 | 77ba0d4e-bc8d-4ae5-b0e2-848feafadadf | TOKEN                | f
(2 rows)
```

```
select * from user_extra where user_id='77ba0d4e-bc8d-4ae5-b0e2-848feafadadf' order BY key;                                                                                 
                 id                  |               user_id                |              key               | value 
--------------------------------------+--------------------------------------+--------------------------------+-------
547a5361-7a67-4d80-a784-708a16f35f0c | 77ba0d4e-bc8d-4ae5-b0e2-848feafadadf | hdx_onboarding_details         | False
18e44af9-45d2-422c-930c-54b9b4d26866 | 77ba0d4e-bc8d-4ae5-b0e2-848feafadadf | hdx_onboarding_details         | False
d3abbc84-4f0f-41d7-938e-0dc183c3006f | 77ba0d4e-bc8d-4ae5-b0e2-848feafadadf | hdx_onboarding_first_login     | False
99ce53ef-777a-48e0-af69-4f977ed1607f | 77ba0d4e-bc8d-4ae5-b0e2-848feafadadf | hdx_onboarding_first_login     | False
05771dff-174f-4ef0-a898-2e5a2e9c4680 | 77ba0d4e-bc8d-4ae5-b0e2-848feafadadf | hdx_onboarding_follows         | False
1027b781-ad45-49b4-8f15-6a89aaa91650 | 77ba0d4e-bc8d-4ae5-b0e2-848feafadadf | hdx_onboarding_follows         | False
3de05827-617a-4874-9891-31392d2d9cff | 77ba0d4e-bc8d-4ae5-b0e2-848feafadadf | hdx_onboarding_friends         | False
a675f153-7aaf-47fb-9fe7-89755e9b7eb2 | 77ba0d4e-bc8d-4ae5-b0e2-848feafadadf | hdx_onboarding_friends         | False
f5ea82a1-fc55-47ab-879d-e9f85f746466 | 77ba0d4e-bc8d-4ae5-b0e2-848feafadadf | hdx_onboarding_org             | False
5ec22342-9618-41fb-9fb9-f52ec27575d5 | 77ba0d4e-bc8d-4ae5-b0e2-848feafadadf | hdx_onboarding_org             | False
52b6481b-8266-4a72-82e4-440a50e656c9 | 77ba0d4e-bc8d-4ae5-b0e2-848feafadadf | hdx_onboarding_user_registered | True
cf59714b-1ade-4e39-a1c7-d50a306eec41 | 77ba0d4e-bc8d-4ae5-b0e2-848feafadadf | hdx_onboarding_user_registered | True
902d4459-df60-4376-9300-ca1ea4965127 | 77ba0d4e-bc8d-4ae5-b0e2-848feafadadf | hdx_onboarding_user_validated  | False
40446cd5-0528-43a6-925c-ff5efb7d385b | 77ba0d4e-bc8d-4ae5-b0e2-848feafadadf | hdx_onboarding_user_validated  | False
```

Apart from checking how this duplicates managed to appear we should also add unique constraints to sqlalchemy/ database so that this can't happen again.

**Comment by amcguire62** [comment] 2015-10-02 07:45
message from user 
Hey Aidan, 
When I click on 'Share data' ,  and log in I get this ''log in email is not available".
I got the email to confirm subscription, I would confirm and get a subscription confirmation email. Though I think it skips a stage. When I tried to sign up with my personal email, before HDX confirming my subscription, I filled out my names, With the official email I don't get to the stage of filling in my names and what I get is this:-

![screen shot 2015-10-02 at 08 44 42](https://cloud.githubusercontent.com/assets/1962335/10241553/ded14f9c-68e1-11e5-829a-6a2f9aa56ef3.png)

Your subscription to our list has been confirmed.
For your records, here is a copy of the information you submitted to us... 
Email Address: bbobson@oxfam.org.uk 
Name:

I use Google Chrome.
The email system is Lotus notes.

**Comment by alexandru-m-g** [comment] 2015-10-02 16:26
The issue for the hotfix is here: #3657

**Comment by alexandru-m-g** [comment] 2015-10-19 12:42
@mbellotti, I might be wrong, but I think that adding the unique=True for sqlalchemy won't affect existing tables. Do we need a SQL patch that @teodorescuserban can run on production ?

**Comment by danmihaila** [comment] 2015-10-19 12:54
I think we should have a nosetest as well to check uniqueness. Also, we need to add a unique constraint for user_extra ( a touple - user_id, key)

**Comment by mbellotti** [comment] 2015-10-20 02:35
@alexandru-m-g You're not wrong, but it's just two simple SQL commands. One to remove existing duplicates, and one to alter the table. Didn't seem worth writing a ckan interface for them -vs- just directly executing them. We will never need to do this again.

**Comment by mbellotti** [comment] 2015-10-20 02:48
@danmihaila Doesn't that completely defeat the purpose of the user_extra table?

**Comment by danmihaila** [comment] 2015-10-20 09:11
@mbellotti regarding Alex's comment - we will need to provide Serban a sql patch/command to run on prod (first we will run it on stag)
re user_extra: I think we should never get same user with the same key two times in db. So, I guess it is ok to have the uniqueness on (user_id, key)

**Comment by mbellotti** [comment] 2015-10-20 11:32
Right but if I set the user_id column to unique then users can only have one extra listed in the db. If I set the key to unique then  only one user in all of HDX can have a specific extra. So why would you want to modify the DB table?

**Comment by danmihaila** [comment] 2015-10-20 11:56
@mbellotti I am talking about adding a unique constraint composed by 2 columns. Lets chat on slack if it is not clear.

**Comment by mbellotti** [comment] 2015-10-20 12:31
So you mean some kind of hash of the two columns values put in a third
brand new column?

**Comment by danmihaila** [comment] 2015-10-20 12:36
I mean to be something like:
CREATE TABLE example (
    a integer,
    b integer,
    c integer,
    UNIQUE (a, c)
);
http://www.postgresql.org/docs/9.4/static/ddl-constraints.html

**Comment by mbellotti** [comment] 2015-10-20 12:46
Well then I don't understand what the point of user_extra is at all.
Package_extra and group_extra (which presumably user_extra was modeled
after) do not seem to have this constraint. So you're restricting the
ultimate usefulness of the table in order to solve a problem we do not
actually have. What happens if in the future there is an extra that we wish
to allow a user to have more than one of?

**_Edit:**_ Oh my mistake, I just looked again at the issue and we DO have this problem. Okay, although it's better to stay consistent with CKAN's way of doing things and add a state flag instead.

**Comment by mbellotti** [comment] 2015-10-21 03:23
Depending on how many duplicates we have... This is the query most efficient for large tables with large number of duplicates:

CREATE TABLE tmp AS (SELECT \* from validation_tokens limit 1) with no data;
INSERT INTO tmp SELECT DISTINCT ON (user_id) \*  FROM validation_tokens;
DROP TABLE validation_tokens;
ALTER TABLE tmp RENAME TO validation_tokens;
ALTER TABLE validation_tokens ADD UNIQUE (user_id)

What's our preferred delivery method here?

**Comment by danmihaila** [comment] 2015-10-21 09:11
do we know how many rows tokens are duplicated? Also, do we know the cause?

**Comment by mbellotti** [comment] 2015-10-21 11:55
Basically it happened because the email validator was case sensitive. That
was fixed in an earlier issue.

**Comment by teodorescuserban** [comment] 2015-10-21 12:02
We encountered multiple validation tokens for same cased email address so
it must be more than this.

Mie, 21 oct. 2015, 14:55, mbellotti notifications@github.com a scris:

**Comment by danmihaila** [comment] 2015-10-21 12:26
Serban, can you send by email a full list of duplicates. I think there were only 2, but lets see.

**Comment by danmihaila** [comment] 2015-10-30 12:33
for user_extra: ALTER TABLE user_extra ADD UNIQUE (user_id,key)
@teodorescuserban I will add the final commands into a google sheet for deploy for next week.

**Closed as completed** 2015-11-09 09:59 UTC
Labels: Bug, High Priority
